# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: vehicle-inventory-backend
  name: vehicle-inventory-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vehicle-inventory-backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/vehicleinventoryapp-default: "true"
        io.kompose.service: vehicle-inventory-backend
    spec:
      containers:
        - args:
            - sh
            - -c
            - python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && opentelemetry-instrument python3 manage.py runserver 0.0.0.0:8001 --noreload
          image: ${REPOSITORY_PREFIX}/pythonsampleapp/vehicle-inventory-service:latest
          name: vehicle-inventory-backend
          env:
            - name: MYSQL_DATABASE
              value: vehicle_inventory
            - name: MYSQL_PASSWORD
              value: ${MYSQL_PASSWORD}
            - name: MYSQL_ROOT_PASSWORD
              value: ${MYSQL_PASSWORD}
            - name: MYSQL_USER
              value: djangouser
            - name: OTEL_SERVICE_NAME
              value: "VehicleInventoryApp"
            - name: OTEL_SMP_ENABLED
              value: "true"
            - name: OTEL_PYTHON_DISTRO
              value: "aws_distro"
            - name: OTEL_PYTHON_CONFIGURATOR
              value: "aws_configurator"
            - name: DJANGO_SETTINGS_MODULE
              value: "VehicleInventoryApp.settings"
            - name: OTEL_AWS_SMP_EXPORTER_ENDPOINT
              value: "http://cloudwatch-agent.amazon-cloudwatch:4315"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://cloudwatch-agent.amazon-cloudwatch:4315"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_TRACES_SAMPLER
              value: "always_on"
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
              hostPort: 8001
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
