# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: Kompose convert -f docker-compose.yaml
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: image-backend
  name: image-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: image-backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: Kompose convert -f docker-compose.yaml
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/imageserviceapp-default: "true"
        io.kompose.service: image-backend
    spec:
      containers:
        - args:
            - sh
            - -c
            - python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && opentelemetry-instrument python3 manage.py runserver 0.0.0.0:8000 --noreload
          image: ${REPOSITORY_PREFIX}/pythonsampleapp/image-service:latest
          name: image-service-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              hostPort: 8000
              protocol: TCP
          resources: {}
          env:
            - name: S3_BUCKET
              value: ${S3_BUCKET}
            - name: OTEL_SERVICE_NAME
              value: "ImageServiceApp"
            - name: OTEL_PYTHON_DISTRO
              value: "aws_distro"
            - name: OTEL_PYTHON_CONFIGURATOR
              value: "aws_configurator"
            - name: DJANGO_SETTINGS_MODULE
              value: "ImageServiceApp.settings"
            - name: OTEL_AWS_SMP_EXPORTER_ENDPOINT
              value: "http://cloudwatch-agent.amazon-cloudwatch:4315"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://cloudwatch-agent.amazon-cloudwatch:4315"
            - name: OTEL_SMP_ENABLED
              value: "true"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_TRACES_SAMPLER
              value: "always_on"
      restartPolicy: Always
status: {}
