## Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
## SPDX-License-Identifier: Apache-2.0

## This workflow aims to run the Application Signals Python end-to-end tests as a canary to
## test the artifacts for App Signals enablement. It will deploy a sample app and remote
## service on two EC2 instances, call the APIs, and validate the generated telemetry,
## including logs, metrics, and traces.
name: App Signals Enablement - Python E2E EC2 Canary Testing
on:
#  schedule:
#    - cron: '*/15 * * * *' # run the workflow every 15 minutes
  workflow_dispatch: # be able to run the workflow on demand
  push:

permissions:
  id-token: write
  contents: read

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        aws-region: ['us-east-1']
    steps:
      - name: Checkout Contrib Repo @ SHA - ${{ github.sha }}
        uses: actions/checkout@v4

      - name: Checkout code and workflow
        uses: actions/checkout@v4
        with:
          repository: aws-observability/aws-application-signals-test-framework
          ref: ec2_e2e_python

      - name: Run workflow
        uses: ./.github/workflows/appsignals-python-e2e-ec2-test.yml
        with:
          aws-region: ${{ matrix.aws-region }}
          caller-workflow-name: 'appsignals-python-e2e-ec2-canary-test'